# Generated by Django 5.2.3 on 2025-07-01 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaitreOuvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Maître d'ouvrage",
                'verbose_name_plural': "Maîtres d'ouvrage",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('specialite', models.CharField(blank=True, max_length=100, verbose_name='Spécialité')),
                ('numero_registre', models.CharField(blank=True, max_length=50, verbose_name='Numéro de registre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prestataire',
                'verbose_name_plural': 'Prestataires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro du marché')),
                ('objet', models.TextField(verbose_name='Objet du marché')),
                ('type', models.CharField(choices=[('travaux', 'Travaux'), ('fournitures', 'Fournitures'), ('services', 'Services'), ('maintenance', 'Maintenance')], max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (€)')),
                ('date_signature', models.DateField(blank=True, null=True, verbose_name='Date de signature')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu'), ('annule', 'Annulé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maitre_ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.maitreouvrage', verbose_name="Maître d'ouvrage")),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.prestataire', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Marché',
                'verbose_name_plural': 'Marchés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire (€)')),
                ('periodicite', models.CharField(blank=True, choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle'), ('ponctuelle', 'Ponctuelle')], max_length=20, verbose_name='Périodicité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='markets.marche', verbose_name='Marché')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Fourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire (€)')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournitures', to='markets.marche', verbose_name='Marché')),
            ],
            options={
                'verbose_name': 'Fourniture',
                'verbose_name_plural': 'Fournitures',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('type', models.CharField(blank=True, choices=[('contrat', 'Contrat'), ('facture', 'Facture'), ('devis', 'Devis'), ('plan', 'Plan'), ('rapport', 'Rapport'), ('photo', 'Photo'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('taille', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Téléchargé par')),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='markets.marche', verbose_name='Marché')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Decompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro')),
                ('periode_debut', models.DateField(blank=True, null=True, verbose_name='Période début')),
                ('periode_fin', models.DateField(blank=True, null=True, verbose_name='Période fin')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant HT (€)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant TTC (€)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('paye', 'Payé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decomptes', to='markets.marche', verbose_name='Marché')),
            ],
            options={
                'verbose_name': 'Décompte',
                'verbose_name_plural': 'Décomptes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro')),
                ('objet', models.TextField(verbose_name='Objet')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('date_execution', models.DateField(blank=True, null=True, verbose_name="Date d'exécution")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_service', to='markets.marche', verbose_name='Marché')),
            ],
            options={
                'verbose_name': 'Ordre de service',
                'verbose_name_plural': 'Ordres de service',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro')),
                ('type', models.CharField(choices=[('reception', 'Réception'), ('constat', 'Constat'), ('reunion', 'Réunion'), ('visite', 'Visite'), ('expertise', 'Expertise'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('date_pv', models.DateField(blank=True, null=True, verbose_name='Date du PV')),
                ('objet', models.TextField(verbose_name='Objet')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvs', to='markets.marche', verbose_name='Marché')),
            ],
            options={
                'verbose_name': 'Procès-Verbal',
                'verbose_name_plural': 'Procès-Verbaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire (€)')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='markets.marche', verbose_name='Marché')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['libelle'],
            },
        ),
    ]
