# Generated by Django 5.2.3 on 2025-07-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='marche',
        ),
        migrations.RemoveField(
            model_name='service',
            name='marche',
        ),
        migrations.AddField(
            model_name='marche',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='marche',
            name='marque',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='marche',
            name='periodicite',
            field=models.CharField(blank=True, choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle'), ('ponctuelle', 'Ponctuelle')], max_length=20, verbose_name='Périodicité'),
        ),
        migrations.AddField(
            model_name='marche',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire (DH)'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (DH)'),
        ),
        migrations.DeleteModel(
            name='Fourniture',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
