# Generated by Django 5.2.3 on 2025-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_remove_maintenance_marche_remove_service_marche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompte',
            name='marche',
        ),
        migrations.RemoveField(
            model_name='ordreservice',
            name='marche',
        ),
        migrations.RemoveField(
            model_name='pv',
            name='marche',
        ),
        migrations.AddField(
            model_name='decompte',
            name='marche',
            field=models.ManyToManyField(blank=True, related_name='décomptes', to='markets.marche'),
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='marche',
            field=models.ManyToManyField(blank=True, related_name='OrdreServices', to='markets.marche'),
        ),
        migrations.AddField(
            model_name='pv',
            name='marche',
            field=models.ManyToManyField(blank=True, related_name='pvs', to='markets.marche'),
        ),
    ]
