# Generated by Django 5.2.4 on 2025-07-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_remove_decompte_marche_remove_ordreservice_marche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompte',
            name='marche',
        ),
        migrations.AlterField(
            model_name='decompte',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant HT (DH)'),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant TTC (DH)'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='marche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decomptes', to='markets.marche'),
        ),
    ]
