# Generated by Django 5.2.4 on 2025-07-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_remove_decompte_marche_alter_decompte_montant_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marche',
            name='rest_a_payer',
            field=models.DecimalField(decimal_places=2, default=222, max_digits=15, verbose_name='Montant (DH)'),
            preserve_default=False,
        ),
    ]
