# Generated by Django 5.2.4 on 2025-07-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_marche_rest_a_payer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompte',
            name='montant_ht',
        ),
        migrations.AlterField(
            model_name='decompte',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Référence '),
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='pv',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Désignation'),
        ),
    ]
