# Generated by Django 5.2.4 on 2025-07-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_remove_decompte_montant_ht_alter_decompte_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marche',
            name='montant_annual',
            field=models.DecimalField(decimal_places=2, default=5555, max_digits=15, verbose_name='Montant Annuel (DH)'),
            preserve_default=False,
        ),
    ]
