# Generated by Django 5.2.4 on 2025-07-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_marche_montant_annual'),
    ]

    operations = [
        migrations.AddField(
            model_name='marche',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='montant_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant Annuel (DH)'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='periodicite',
            field=models.CharField(blank=True, choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle'), ('ponctuelle', 'Ponctuelle')], max_length=20, null=True, verbose_name='Périodicité'),
        ),
    ]
