# Generated by Django 5.2.4 on 2025-07-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_marche_quantite_alter_marche_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompte',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=' description'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=15, verbose_name='Montant HT (DH)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decompte',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=15, verbose_name='TVA (%)'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='unite_de_mesure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unité de mesure'),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
