# Generated by Django 5.2.4 on 2025-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_decompte_description_decompte_montant_ht_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompte',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=15, verbose_name='TVA (%)'),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='unite_de_mesure',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unité de mesure'),
        ),
    ]
