# Generated by Django 5.2.4 on 2025-07-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_alter_decompte_montant_ttc_alter_decompte_tva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompte',
            name='tva',
        ),
    ]
