# Generated by Django 5.2.4 on 2025-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0011_remove_decompte_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompte',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=15, verbose_name='TVA (%)'),
        ),
    ]
