# Generated by Django 5.2.4 on 2025-07-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0012_decompte_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompte',
            name='tva',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='TVA (%)'),
        ),
    ]
