# Generated by Django 5.2.4 on 2025-07-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0013_alter_decompte_tva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompte',
            name='tva',
        ),
    ]
