# Generated by Django 5.2.4 on 2025-07-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0014_remove_decompte_tva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompte',
            name='montant_ht',
        ),
        migrations.AddField(
            model_name='decompte',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=15, verbose_name='TVA (%)'),
        ),
    ]
