# Generated by Django 5.2.4 on 2025-07-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0015_remove_decompte_montant_ht_decompte_tva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompte',
            name='tva',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='unite_de_mesure',
        ),
        migrations.AlterField(
            model_name='decompte',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
