# Generated by Django 5.2.4 on 2025-07-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0016_remove_decompte_tva_remove_decompte_unite_de_mesure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompte',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=15, verbose_name='Montant HT (DH)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decompte',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=15, verbose_name='TVA (%)'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='unite_de_mesure',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unité de mesure'),
        ),
    ]
