# Generated by Django 5.2.4 on 2025-07-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0017_decompte_montant_ht_decompte_tva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompte',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
    ]
