# Generated by Django 5.2.4 on 2025-08-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0018_alter_decompte_montant_ttc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordreservice',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='ordres_service/', verbose_name='Fichier joint (PDF)'),
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observations complémentaires'),
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='signataire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signataire'),
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='type',
            field=models.CharField(choices=[('commencement', 'Commencement'), ('arret', 'Arrêt'), ('reprise', 'Reprise'), ('resiliation', 'Résiliation'), ('reception', 'Réception'), ('annule', 'Annulé'), ('autre', 'Autre')], default='Commencement', max_length=20, verbose_name="Type d'ordre de service"),
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='date_execution',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'exécution prévue"),
        ),
        migrations.RemoveField(
            model_name='ordreservice',
            name='marche',
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='marche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordres_service', to='markets.marche', verbose_name='Marché concerné'),
        ),
    ]
