# Generated by Django 5.2.4 on 2025-08-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0019_ordreservice_fichier_ordreservice_observations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompte',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='decompte/', verbose_name='Fichier joint (PDF)'),
        ),
        migrations.AddField(
            model_name='pv',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='pv/', verbose_name='Fichier joint (PDF)'),
        ),
    ]
