# Generated by Django 5.2.4 on 2025-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0020_decompte_fichier_pv_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='signataire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signataire'),
        ),
        migrations.AddField(
            model_name='pv',
            name='signataire_deux',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signataire'),
        ),
        migrations.AddField(
            model_name='pv',
            name='signataire_trois',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signataire'),
        ),
    ]
