# Generated by Django 5.2.4 on 2025-08-26 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0021_pv_signataire_pv_signataire_deux_pv_signataire_trois'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pv',
            name='marche',
        ),
        migrations.AddField(
            model_name='pv',
            name='marche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvs', to='markets.marche'),
        ),
    ]
