# Generated by Django 5.2.4 on 2025-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0022_remove_pv_marche_pv_marche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv',
            name='type',
            field=models.CharField(choices=[('reception provisoire', 'Réception provisoire'), ('reception defintive', 'Réception defintive'), ('constat', 'Constat'), ('reunion', 'Réunion'), ('visite', 'Visite'), ('expertise', 'Expertise'), ('autre', 'Autre')], max_length=20, verbose_name='Type'),
        ),
    ]
