# Generated by Django 5.2.4 on 2025-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0023_alter_pv_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv',
            name='type',
            field=models.CharField(choices=[('reception provisoire', 'Réception provisoire'), ('reception defintive', 'Réception defintive'), ('reception defintive', 'Réception defintive parcielle'), ('autre', 'Autre')], max_length=20, verbose_name='Type'),
        ),
    ]
