# Generated by Django 5.2.4 on 2025-09-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0024_alter_pv_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='periode_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Période début'),
        ),
        migrations.AddField(
            model_name='pv',
            name='periode_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Période fin'),
        ),
    ]
