# Generated by Django 5.2.4 on 2025-09-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0025_pv_periode_debut_pv_periode_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='fonction_signataire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction du signataire'),
        ),
        migrations.AddField(
            model_name='pv',
            name='fonction_signataire_deux',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction du signataire'),
        ),
        migrations.AddField(
            model_name='pv',
            name='fonction_signataire_trois',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction du signataire'),
        ),
    ]
