# Generated by Django 5.2.4 on 2025-09-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0026_pv_fonction_signataire_pv_fonction_signataire_deux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='maitre_ouvrage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='markets.maitreouvrage', verbose_name="Maître d'ouvrage"),
        ),
        migrations.AlterField(
            model_name='marche',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='markets.prestataire', verbose_name='Prestataire'),
        ),
        migrations.AlterField(
            model_name='pv',
            name='signataire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signataire 1'),
        ),
        migrations.AlterField(
            model_name='pv',
            name='signataire_deux',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signataire 2'),
        ),
        migrations.AlterField(
            model_name='pv',
            name='signataire_trois',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signataire 3'),
        ),
    ]
