# Generated by Django 5.2.4 on 2025-09-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0027_alter_marche_maitre_ouvrage_alter_marche_prestataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='periodicite',
            field=models.CharField(blank=True, choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle'), ('ponctuelle', 'Ponctuelle'), ('prorata', 'Prorata (calcul par jours)')], default='trimestrielle', help_text="Choisir 'Prorata' pour un calcul basé sur le nombre exact de jours", max_length=20, null=True, verbose_name='Périodicité'),
        ),
    ]
