# Generated by Django 5.2.4 on 2025-09-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0028_alter_marche_periodicite'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompte',
            name='type',
            field=models.CharField(choices=[('provisoire', 'Provisoire'), ('definitif', 'Définitif'), ('definitif partiel', 'Définitif partiel'), ('autre', 'Autre')], default='provisoire', max_length=20, verbose_name='Type de decompte'),
        ),
    ]
