# Generated by Django 5.2.4 on 2025-09-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0029_decompte_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompte',
            name='periodicite',
            field=models.CharField(blank=True, choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle'), ('ponctuelle', 'Ponctuelle'), ('prorata', 'Prorata (calcul par jours)')], default='trimestrielle', help_text="Choisir 'Prorata' pour un calcul basé sur le nombre exact de jours", max_length=20, null=True, verbose_name='Périodicité'),
        ),
    ]
