# Generated by Django 5.2.4 on 2025-09-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0030_decompte_periodicite'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_doc',
            field=models.DateField(blank=True, null=True, verbose_name='Date du document'),
        ),
    ]
