# Generated by Django 5.2.4 on 2025-09-17 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0031_document_date_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='marche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='markets.marche', verbose_name='Marché'),
        ),
    ]
