# Generated by Django 5.2.4 on 2025-10-08 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0032_alter_document_marche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'acompte")),
                ('objet', models.TextField(blank=True, null=True, verbose_name="Objet de l'acompte")),
                ('date_acompte', models.DateField(verbose_name="Date de l'acompte")),
                ('periode_debut', models.DateField(verbose_name='Période début')),
                ('periode_fin', models.DateField(verbose_name='Période fin')),
                ('pourcentage_realisation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de réalisation (%)')),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='acomptes/', verbose_name='Document justificatif (PDF)')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acomptes', to='markets.marche', verbose_name='Marché')),
            ],
        ),
        migrations.AddField(
            model_name='decompte',
            name='acompte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decompte', to='markets.acompte'),
        ),
    ]
