# Generated by Django 5.2.4 on 2025-10-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0033_acompte_decompte_acompte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompte',
            name='periodicite',
            field=models.CharField(blank=True, choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle'), ('ponctuelle', 'Ponctuelle'), ('prorata', 'Prorata (calcul par jours)')], default='trimestrielle', help_text="Choisir 'Prorata' pour un calcul basé sur le nombre exact de jours", max_length=20, null=True, verbose_name='Périodicité'),
        ),
    ]
