# Generated by Django 5.2.4 on 2025-10-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0034_alter_decompte_periodicite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompte',
            name='unite_de_mesure',
        ),
    ]
