# Generated by Django 5.2.4 on 2025-10-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0035_remove_decompte_unite_de_mesure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du signataire')),
                ('fonction', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonction')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
            ],
        ),
        migrations.RemoveField(
            model_name='pv',
            name='fonction_signataire',
        ),
        migrations.RemoveField(
            model_name='pv',
            name='fonction_signataire_deux',
        ),
        migrations.RemoveField(
            model_name='pv',
            name='fonction_signataire_trois',
        ),
        migrations.RemoveField(
            model_name='pv',
            name='signataire',
        ),
        migrations.RemoveField(
            model_name='pv',
            name='signataire_deux',
        ),
        migrations.RemoveField(
            model_name='pv',
            name='signataire_trois',
        ),
    ]
