# Generated by Django 5.2.4 on 2025-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0036_signataire_remove_pv_fonction_signataire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='signataires',
            field=models.ManyToManyField(related_name='pvs', to='markets.signataire', verbose_name='Signataires'),
        ),
    ]
