# Generated by Django 5.2.4 on 2025-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0037_pv_signataires'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='cnss',
            field=models.CharField(blank=True, verbose_name='CNSS'),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='compte',
            field=models.CharField(blank=True, verbose_name='compte'),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='patente',
            field=models.CharField(blank=True, verbose_name='patente'),
        ),
    ]
