# Generated by Django 5.2.4 on 2025-10-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0038_prestataire_cnss_prestataire_compte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='representant',
            field=models.TextField(blank=True, verbose_name='Répresentant'),
        ),
    ]
