# Generated by Django 5.2.4 on 2025-10-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0039_prestataire_representant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='representant',
            field=models.CharField(blank=True, verbose_name='Répresentant'),
        ),
    ]
