# Generated by Django 5.2.4 on 2025-10-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0040_alter_prestataire_representant'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='capital',
            field=models.CharField(blank=True, max_length=100, verbose_name='Capital'),
        ),
    ]
