# Generated by Django 5.2.4 on 2025-11-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0042_alter_decompte_periodicite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decompte',
            options={},
        ),
        migrations.CreateModel(
            name='LigneDecompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_prix', models.ImageField(blank=True, null=True, upload_to='')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('unite', models.CharField(blank=True, max_length=50, null=True)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=5, null=True)),
                ('tva', models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=5, null=True)),
                ('decompte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='markets.decompte')),
            ],
        ),
    ]
