# Generated by Django 5.2.4 on 2025-11-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0043_alter_decompte_options_lignedecompte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decompte',
            options={'ordering': ['-created_at'], 'verbose_name': 'Décompte', 'verbose_name_plural': 'Décomptes'},
        ),
    ]
