# Generated by Django 5.2.4 on 2025-11-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0044_alter_decompte_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LigneDecompte',
        ),
    ]
