# Generated by Django 5.2.4 on 2025-11-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0045_delete_lignedecompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompte',
            name='designtion1',
            field=models.CharField(blank=True, null=True, verbose_name=' Désignation'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='designtion2',
            field=models.CharField(blank=True, null=True, verbose_name=' Désignation'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='designtion3',
            field=models.CharField(blank=True, null=True, verbose_name=' Désignation'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='numero_prix1',
            field=models.IntegerField(blank=True, null=True, verbose_name=' N° des prix'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='numero_prix2',
            field=models.IntegerField(blank=True, null=True, verbose_name=' N° des prix'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='numero_prix3',
            field=models.IntegerField(blank=True, null=True, verbose_name=' N° des prix'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='prix_unitaire1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=' Prix unitaire'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='prix_unitaire2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=' Prix unitaire'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='prix_unitaire3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name=' Prix unitaire'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='qte1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='qte2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='qte3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='unite_mesure1',
            field=models.CharField(blank=True, null=True, verbose_name=' Unité de mesure'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='unite_mesure2',
            field=models.CharField(blank=True, null=True, verbose_name=' Unité de mesure'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='unite_mesure3',
            field=models.CharField(blank=True, null=True, verbose_name=' Unité de mesure'),
        ),
    ]
