# Generated by Django 5.2.4 on 2025-11-11 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0046_decompte_designtion1_decompte_designtion2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompte',
            name='designtion1',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='designtion2',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='designtion3',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='numero_prix1',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='numero_prix2',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='numero_prix3',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='prix_unitaire1',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='prix_unitaire2',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='prix_unitaire3',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='qte1',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='qte2',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='qte3',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='unite_mesure1',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='unite_mesure2',
        ),
        migrations.RemoveField(
            model_name='decompte',
            name='unite_mesure3',
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_prix', models.CharField(max_length=50)),
                ('designation', models.TextField()),
                ('unite_mesure', models.CharField(max_length=50)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='markets.marche')),
            ],
        ),
    ]
