# Generated by Django 5.2.4 on 2025-12-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0047_remove_decompte_designtion1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompte',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
