# Generated by Django 5.2.4 on 2026-01-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0048_alter_decompte_montant_ttc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='rest_a_payer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Rest a payer (DH)'),
        ),
    ]
