# Generated by Django 5.2.4 on 2026-01-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0049_alter_marche_rest_a_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompte',
            name='montant_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
